declare module 'qrcode' {
  /** Declaration file generated by dts-gen */

  export function create(data: any, options?: any): any;

  export function toBuffer(text: any, opts?: any, cb?: any): any;

  export function toCanvas(p0: any, p1: any, p2: any, p3: any): any;

  export function toDataURL(text: any, opts?: any, cb?: any): any;

  export function toFile(path: any, text: any, opts: any, cb: any, ...args: any[]): any;

  export function toFileStream(stream: any, text: any, opts: any, ...args: any[]): void;

  export function toString(text: any, opts?: any, cb?: any): any;

}
