declare module 'vue3-mq' {
    /** Declaration file generated by dts-gen */
    export function updateBreakpoints({ breakpoints: e, preset: t }: any): any;

    export function useMq(): any;

    export namespace MqResponsive {
        const name: string;

        const props: {
            dark: {
                default: boolean;
                type: any;
            };
            group: {
                default: boolean;
                type: any;
            };
            landscape: {
                default: boolean;
                type: any;
            };
            light: {
                default: boolean;
                type: any;
            };
            listTag: {
                default: string;
                type: any;
            };
            portrait: {
                default: boolean;
                type: any;
            };
            tag: {
                default: string;
                type: any;
            };
            target: any[];
        };

        function setup(...args: any[]): void;

    }

    export namespace Vue3Mq {
        function install(e: any, { preset: t = 'bootstrap5', breakpoints: n, defaultBreakpoint: i, defaultOrientation: s = 'landscape', defaultTheme: l }: any): void;
    }
}